org: amodinho
app: serverlessnextjsdemo
service: serverless-nextjs-demo

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  environment:
      SLS_DEBUG: true

serverless-nextjs-demo:
  component: serverless-next.js


